name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cloc
      run: sudo apt-get install -y cloc
    - name: Count lines of code
      id: cloc
      run: |
        cloc . > cloc_output.txt
        cat cloc_output.txt
    - name: Create comment with cloc result
      uses: actions/github-script@v3
      with:
        script: |
          const fs = require('fs');
          const clocOutput = fs.readFileSync('cloc_output.txt', 'utf8');
          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body: `Lines of Code Report:\n\`\`\`\n${clocOutput}\n\`\`\``
          });

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '8.5'

    - name: Build with Gradle 8.5
      run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '8.5'

    - name: Generate and submit dependency graph
      run: gradle dependencies
